[project]
name = "crystallograpy"
version = "0.1.0"
description = "Lightweight Python utilities about crystallography properties"
authors = [
    {name = "alexhernandezgarcia", email = "alex.hernandez-garcia@mila.quebec"},
]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "PyYAML >=6.0.1",
]
license = "Hippocratic-3.0-core"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/milaforscience/crystallograpy"
Issues = "https://github.com/milaforscience/crystallograpy/issues"

[tool.setuptools]
package-dir = {"" = "src"}

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project.optional-dependencies]
dev = [
    "black >=23.9.1",
    "flake8 >=6.1.0",
    "isort >=5.12.0",
    "ipdb >=0.13.13",
    "jupyter >=1.0.0",
    "pylint >=2.17.6",
    "pytest >=7.4.2",
    "pytest-repeat >=0.9.1",
]
